---

- src: https://github.com/dev-sec/ansible-ssh-hardening
  version: 9.7.0

- src: https://github.com/geerlingguy/ansible-role-docker
  version: 5.2.1

- src:  https://github.com/robertdebock/ansible-role-autofs
  version: 2.1.3

- src: https://github.com/bertvv/ansible-role-hosts
  version: v1.2.0

- src: https://github.com/FueledbyJordan/ansible-role-utilities
  version: master
