---

- src: https://github.com/dev-sec/ansible-ssh-hardening
  version: 9.7.0

- src: https://github.com/geerlingguy/ansible-role-docker
  version: 5.2.1

- src: https://github.com/robertdebock/ansible-role-autofs
  version: 2.1.3

- src: https://github.com/bertvv/ansible-role-hosts
  version: v1.2.0

- src: https://github.com/FueledbyJordan/ansible-role-utilities
  version: master

- src: https://github.com/ryandaniels/ansible-role-create-users
  version: 1.0.7

- src: https://github.com/geerlingguy/ansible-role-firewall
  version: 2.5.0

- src: https://github.com/FueledbyJordan/ansible-role-docker-compose
  version: master

- src: https://github.com/FueledbyJordan/ansible-role-home-assistant
  version: master

- src: https://github.com/FueledbyJordan/ansible-role-rclone-supercronic
  version: master
