---

- hosts: server
  become: true
  vars_files:
    - vars/main.yml
    - vars/secrets.yml

  roles:
    - role: ansible-role-create-users
    - role: ansible-ssh-hardening
    - role: ansible-role-firewall
    - role: ansible-role-docker
    - role: ansible-role-autofs
    - role: ansible-role-hosts
    - role: ansible-role-utilities
    - role: ansible-role-docker-compose
    - role: ansible-role-home-assistant
